#Direct the main healthcheck to port 8000
#Direct the face-bokeh to port 8001
#Direct the face-emotion to port 8002
version: '3.7'

services: 

    bitcoin-model:
        build: ./bitcoin-model
        container_name: bitcoin-model-cntr
        image: bitcoin-model-img
        ports: 
            - 8003:8000
        env_file: 
            - .env
    
    backend:
        build: ./backend
        container_name: backend-cntr
        image: backend-img
        ports:
            - 8001:8000

    bitcoin-main:
        build: ./frontend
        container_name: frontend-cntr
        image: frontend-img
        ports:
            - 8501:8501
        env_file: 
            - .env
        depends_on:
            - bitcoin-model
            - inference-server
            - backend


    inference-server:
        container_name: triton
        env_file:
            .aws.env
        ports:
            - 8000:8000
            - 8002:8002
        image: nvcr.io/nvidia/tritonserver:22.06-py3
        command:
            ['tritonserver', '--model-repository=s3://fb-bitcoin-capstone/triton-model/'] 
