base_folder: '.'
v2_query:  '(Bitcoin OR #Bitcoin OR #BTC OR #btc) lang:en -is:retweet'
env_config_path: '.'
model_name: 'ElKulako/cryptobert'
inference: 'triton' #'hugging-face'
output_dir: 'output'
input_dir: '../dataset/v1'
epochs: 1
mlflow_expt: "batch_serving"
mlflow_artifact: "hf_model"
root_path: "triton-model/bitcoin-model/"
s3_bucket: "shobha-mur-week1"   #"fb-bitcoin-capstone"
