base_folder: '.'
v2_query:  '(BITCOIN OR #Bitcoin OR #bitcoin OR #BTC OR #btc OR #XBT OR #xbt) lang:en -is:retweet'
env_config_path: '.'
model_name: 'ElKulako/cryptobert'
inference: 'triton' #'hugging-face'
output_dir: 'output'
input_dir: '../dataset/v1'
epochs: 1
mlflow_expt: "capstone"
mlflow_artifact: "hf_model"
root_path: "triton-model/bitcoin-model/"
s3_bucket: "fb-bitcoin-capstone"   #"shobha-mur-week1"
num_tweets: 15
